Adding install cocoapods build step

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -56,6 +56,11 @@ jobs:
         working-directory: ios
         run: bundle install
 
+      - name: 🛠 Install CocoaPods
+        run: |
+          sudo gem uninstall cocoapods -aIx || true          # clean up any half-installed copy
+          sudo gem install cocoapods -v 1.15.2 --no-document # pick a known-good version
+
       - name: 📦 Install CocoaPods dependencies
         working-directory: ios
         run: |
